# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Matheus-IHS/teste_private_repo
  branch: main

# local_backend: true

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: ""
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }
