backend:
  name: github
  repo: Matheus-IHS/teste_private_repo
  branch: main
  base_url: https://sveltia-cms-auth.matheus-barreira.workers.dev/

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: docs
    label: Docs
    label_singular: Docs
    folder: /docs
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
