# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: local/docs
  branch: main

local_backend: true

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Documentação"
    folder: "app/docs"
    extension: "md"
    format: "frontmatter"
    create: true
    nested:
      depth: 3
    meta:
      path:
        widget: string
        label: Caminho
        index_file: index
    fields:
      - { label: "Título", name: "title", widget: "string", required: false }
      - { label: "Posição no Sidebar", name: "sidebar_position", widget: "number", required: false, value_type: "int" }
      - { label: "Label no Sidebar", name: "sidebar_label", widget: "string", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
