# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Matheus-IHS/teste_private_repo
  branch: main

# local_backend: true

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Documentação"
    folder: "/"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}" # Dictates the filename (e.g., title-of-page.md)
    filter: { field: "title", match: ".*" }
    exclude:
      - "README.md"
      - "node_modules"
      - ".git"
    fields:
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Posição no Sidebar", name: "sidebar_position", widget: "number", required: false, value_type: "int" }
      - { label: "Label no Sidebar", name: "sidebar_label", widget: "
